main: pl.plajer.buildbattle4.Main
version: ${project.version}
name: BuildBattle
softdepend: [Vault, PlaceholderAPI, Citizens]
authors: [Plajer, TomTheDeveloper]

commands:
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]
  buildbattleadmin:
    aliases: [buildba, bba]

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.updatenotify: true
      buildbattle.admin: true
      buildbattle.admin.sign.create: true
      buildbattle.admin.sign.break: true
      buildbattle.admin.stopgame: true
      buildbattle.admin.addnpc: true
      buildbattle.admin.addsign: true
      buildbattle.admin.reload: true
      buildbattle.admin.forcestart: true
      buildbattle.admin.addplot: true
      buildbattle.admin.removeplot: true
      buildbattle.admin.plotwand: true
      buildbattle.admin.list: true
      buildbattle.admin.delete: true
      buildbattle.admin.create: true
      buildbattle.admin.settheme: true
      buildbattle.admin.supervotes.set: true
      buildbattle.admin.supervotes.add: true
      buildbattle.command.bypass: true